name: flutter_book_drift
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.29.0
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

